import type { NextPage } from 'next'
import Script from 'next/script'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2 data-gtm-text-click="ketsugou-danshi_01" data-gtm-calc-text-click="true">
              結合男子
            </h2>
            <h3>
              <a id="ketsugou-danshi" href="https://www.jp.square-enix.com/ketsugou-danshi/" data-gtm-external-link="true">
                公式サイトへ
              </a>
            </h3>
            <p data-gtm-text-click="ketsugou-danshi_02" data-gtm-calc-text-click="true">
              万物を呑み込み同化する暗黒の絶対虚無『デッドマター』
            </p>
            <div data-gtm-text-click="ketsugou-danshi_03" data-gtm-calc-text-click="true">
              ここ『結倭ノ国』に
              デッドマターの脅威に
              敢然と立ち向かう者たちがいた
              元素の力を宿す『志献官』である
            </div>
          </div>

          <Script id="data-layer-sample" strategy="afterInteractive">
            {`
              window.dataLayer = window.dataLayer || [];
              dataLayer.push({
                currentTime: new Date().toString()
              })
            `}
          </Script>

          <div className={styles.card}>
            <h2 data-gtm-text-click="octopath_traveler_2_01" data-gtm-calc-text-click="true">
              オクトパストラベラーII
            </h2>
            <h3>
              <a id="octopath_traveler_2" href="https://www.jp.square-enix.com/octopathtraveler2/" data-gtm-external-link="true">
                公式サイトへ
              </a>
            </h3>
            <p data-gtm-text-click="octopath_traveler_2_02" data-gtm-calc-text-click="true">旅立とう、きみだけの物語へ――</p>
            <p data-gtm-text-click="octopath_traveler_2_03" data-gtm-calc-text-click="true">COMING 2023.2.24</p>
          </div>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
