on: [push]

jobs:
  deploy_nuxtjs:
    name: Deploy NuxtJS
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.ref_name }}
    steps:
      - name: $ git clone する
        uses: actions/checkout@v3
      - name: Node.js のセットアップを行う
        uses: actions/setup-node@v3
        with:
          # 自前ビルドして静的ファイルを置くだけの場合は v18 でも OK
          node-version-file: "nuxt3_monorepo/.node-version"
          cache: yarn
          cache-dependency-path: nuxt3_monorepo/yarn.lock
      - name: $ yarn install を実行する
        run: |
          cd nuxt3_monorepo
          yarn install
      - name: NuxtJS を SSG する
        run: |
          cd nuxt3_monorepo
          yarn generate
      - name: デプロイする
        # https://github.com/cloudflare/wrangler-action
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          # Account ID は $ wrangler whoami で確認することができる
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish nuxt3_monorepo/.output/public --project-name=training-ga4-by-nuxt3 --branch=${BRANCH_NAME}
