name: Step の途中で差分があれば自動で PR して Merge する

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'

jobs:
  pr_and_merge:
    name: 自動で PR して Merge する
    runs-on: ubuntu-latest
    steps:
      # 次の Step 以降に ${{ env.変数名 }} で参照できる
      - name: 全体を通して使う変数を定義する
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo CURRENT_DATETIME=`date "+%Y%m%d_%H%M%S"` >> $GITHUB_ENV
          echo CURRENT_DATETIME_WITH_DIVIDERS=`date "+%Y/%m/%d %H:%M:%S"` >> $GITHUB_ENV
      - name: $ git clone する
        uses: actions/checkout@v3
      - name: $ git diff を実行して差分がある場合には Pull Request を出す
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: 'Asia/Tokyo'
        # $ git diff --exit-code は、差分がある時は "1 = error" を返し、無いときは "0" を返す
        run: |
          # 新規ファイル追加時には -N を経ないと差分が検出されない
          git add -N -A

          if ! git diff --exit-code --quiet
          then
            git config --global user.email "takiya@toran.sakura.ne.jp"
            git config --global user.name "nikukyugamer"

            git switch -c update_${{ env.CURRENT_DATETIME }}
            git add -A
            git commit -m "更新した"
            git push --set-upstream origin update_${{ env.CURRENT_DATETIME }}

            gh version

            gh pr create --title "更新した (${{ env.CURRENT_DATETIME_WITH_DIVIDERS }})" --body "- 更新した (${{ env.CURRENT_DATETIME_WITH_DIVIDERS }})"

            # マージまで自動でやる
            gh pr merge --squash --delete-branch update_${{ env.CURRENT_DATETIME }}
          else
            echo "差分が無いためプルリクエストは作成せずに終了します。"
          fi
