name: Step の途中で差分があれば自動で PR して Merge する

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'

jobs:
  pr_and_merge:
    name: 自動で PR して Merge する
    runs-on: ubuntu-latest
    steps:
      - name: $ git clone する
        uses: actions/checkout@v3
      - name: $ touch hoge する
        run: |
          touch hoge
      - name: $ git diff を実行して差分があるかどうかをチェックする
        id: git_diff
        # $ git diff --exit-code は、差分がある時は "1 = error" を返し、無いときは "0" を返す
        continue-on-error: true
        run: |
          git config --global user.email "takiya@toran.sakura.ne.jp"
          git config --global user.name "nikukyugamer"

          git add .
          git diff --cached --exit-code --quiet
      - name: 差分が無いときにはプルリクエストは出さない
        if: steps.git_diff.outcome == 'success'
        run: |
          echo "差分が無いためプルリクエストは作成せずに終了します。"
      - name: 差分があるときにはプルリクエストを提出する
        if: steps.git_diff.outcome == 'failure'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: 'Asia/Tokyo'
        run: |
          CURRENT_DATETIME=`date "+%Y%m%d_%H%M%S"`
          CURRENT_DATETIME_WITH_DIVIDERS=`date "+%Y/%m/%d %H:%M:%S"`

          git switch -c update_${CURRENT_DATETIME}

          git commit -m "更新した"
          git push --set-upstream origin update_${CURRENT_DATETIME}

          gh version

          gh pr create --title "更新した (${CURRENT_DATETIME_WITH_DIVIDERS})" --body "- 更新した"
      - name: 差分があるときはコミットしてプッシュする
        run : |
          echo 'TODO: 差分があるときはコミットしてプッシュする'
